name: monexec
version: git
summary: Light supervisor with optional Consul autoregistration
icon: docs/logo.svg
description: |
  It’s tool for controlling processes like a supervisord but with some important features:

  - Easy to use - no dependencies. Just a single binary file pre-compilled for most major platforms
  - Easy to hack - monexec can be used as a Golang library with clean and simple architecture
  - Integrated with Consul - optionally, monexec can register all running processes as services and deregister on fail
  - Optional notification to Telegram
  - Supports gracefull and fast shutdown by signals
  - Developed for used inside Docker containers
  - Different strategies for processes
  - Support template-based email notification
  - Support HTTP notification
  - REST API (see swagger.yaml)
  - Web UI (if REST API enabled)

  Source code licensed under MIT and can be obtained via https://github.com/reddec/monexec

grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.11.2
  cli:
    after: [go]
    plugin: go
    go-importpath: github.com/reddec/monexec

apps:
  monexec:
    command: bin/monexec
    plugs:
      - network